---

- name: Instalar Apache
  hosts: webserver
  become: true

  tasks:
    - name: Instalar Apache
      apt: name=apache2 update_cache=yes state=latest

    - name: Inicia Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Reinicia Apache
      service: name=apache2 state=restarted
